CREATE TABLE IF NOT EXISTS `youcai_insect_trend_suggest` (
  `id` varchar(32) NOT NULL COMMENT '主键ID',
  `base_id` varchar(32) NOT NULL COMMENT '基地ID',
  `base_name` varchar(100) DEFAULT NULL COMMENT '基地名称',
  `analysis_date` date NOT NULL COMMENT '虫情日期',
  `analysis_time` datetime DEFAULT NULL COMMENT '分析时间',
  `image_url` varchar(1000) DEFAULT NULL COMMENT '最新虫情图片',
  `insect_summary` varchar(1000) DEFAULT NULL COMMENT '虫子名称和数量',
  `trend_analysis` text COMMENT '害虫趋势分析',
  `control_suggestion` text COMMENT '防治建议',
  `raw_insect_json` longtext COMMENT '原始虫情JSON',
  `raw_image_json` longtext COMMENT '原始图片JSON',
  `status` varchar(20) DEFAULT NULL COMMENT '生成状态：SUCCESS/FAILED/FALLBACK',
  `error_msg` varchar(1000) DEFAULT NULL COMMENT '错误信息',
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(32) DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `sys_org_code` varchar(64) DEFAULT NULL COMMENT '所属部门',
  `del_flag` tinyint DEFAULT 0 COMMENT '删除标志（0-正常，1-删除）',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_youcai_insect_trend_date_base` (`analysis_date`, `base_id`),
  KEY `idx_youcai_insect_trend_date` (`analysis_date`),
  KEY `idx_youcai_insect_trend_base` (`base_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='基地虫情趋势与防治建议';
